export const questionPlay = [
  {
    id: 1,
    texto: "La vida es bella.",
    autor: "Roberto Benigni",
    nombre: "Película: La vida es bella",
    textColor: "white",
  },
  {
    id: 2,
    texto: "El tiempo es oro.",
    autor: "Proverbio popular",
    nombre: "Refrán",
    textColor: "white",
  },
  {
    id: 3,
    texto: "Carpe diem.",
    autor: "Horacio",
    nombre: "Odas",
    textColor: "white",
  },
  {
    id: 4,
    texto: "Vive y deja vivir.",
    autor: "Refrán popular",
    nombre: "Refrán",
    textColor: "white",
  },
  {
    id: 5,
    texto: "El saber no ocupa lugar.",
    autor: "Proverbio popular",
    nombre: "Refrán",
    textColor: "white",
  },
  {
    id: 6,
    texto: "La unión hace la fuerza.",
    autor: "Esopo",
    nombre: "Fábulas de Esopo",
    textColor: "white",
  },
  {
    id: 7,
    texto: "Más vale tarde que nunca.",
    autor: "Geoffrey Chaucer",
    nombre: "Los cuentos de Canterbury",
    textColor: "white",
  },
  {
    id: 8,
    texto: "La práctica hace al maestro.",
    autor: "Proverbio popular",
    nombre: "Refrán",
    textColor: "white",
  },
  {
    id: 9,
    texto: "A mal tiempo, buena cara.",
    autor: "Proverbio popular",
    nombre: "Refrán",
    textColor: "white",
  },
  {
    id: 10,
    texto: "El tiempo lo cura todo.",
    autor: "Proverbio popular",
    nombre: "Refrán",
    textColor: "white",
  },
  {
    id: 11,
    texto: "Ojos que no ven, corazón que no siente.",
    autor: "Proverbio popular",
    nombre: "Refrán",
    textColor: "white",
  },
  {
    id: 12,
    texto: "Haz el bien sin mirar a quién.",
    autor: "Proverbio popular",
    nombre: "Refrán",
    textColor: "white",
  },
  {
    id: 13,
    texto: "Quien mucho abarca, poco aprieta.",
    autor: "Proverbio popular",
    nombre: "Refrán",
    textColor: "white",
  },
  {
    id: 14,
    texto: "El que persevera, alcanza.",
    autor: "Proverbio popular",
    nombre: "Refrán",
    textColor: "white",
  },
  {
    id: 15,
    texto: "A quien madruga, Dios le ayuda.",
    autor: "Proverbio popular",
    nombre: "Refrán",
    textColor: "white",
  },
  {
    id: 16,
    texto: "No hay mal que por bien no venga.",
    autor: "Proverbio popular",
    nombre: "Refrán",
    textColor: "white",
  },
  {
    id: 17,
    texto: "Más vale prevenir que curar.",
    autor: "Proverbio popular",
    nombre: "Refrán",
    textColor: "white",
  },
  {
    id: 18,
    texto: "De tal palo, tal astilla.",
    autor: "Proverbio popular",
    nombre: "Refrán",
    textColor: "white",
  },
  {
    id: 19,
    texto: "En casa de herrero, cuchillo de palo.",
    autor: "Proverbio popular",
    nombre: "Refrán",
    textColor: "white",
  },
  {
    id: 20,
    texto: "El conocimiento es poder.",
    autor: "Francis Bacon",
    nombre: "Meditationes Sacrae",
    textColor: "white",
  },
  {
    id: 21,
    texto: "Divide y vencerás.",
    autor: "Julio César",
    nombre: "Estrategia militar",
    textColor: "white",
  },
  {
    id: 22,
    texto: "Pienso, luego existo.",
    autor: "René Descartes",
    nombre: "Discurso del método",
    textColor: "white",
  },
  {
    id: 23,
    texto: "Ser o no ser, esa es la cuestión.",
    autor: "William Shakespeare",
    nombre: "Hamlet",
    textColor: "white",
  },
  {
    id: 24,
    texto: "La esperanza es lo último que se pierde.",
    autor: "Proverbio popular",
    nombre: "Refrán",
    textColor: "white",
  },
  {
    id: 25,
    texto: "Lo que no te mata, te hace más fuerte.",
    autor: "Friedrich Nietzsche",
    nombre: "Crepúsculo de los ídolos",
    textColor: "white",
  },
  {
    id: 26,
    texto: "La paciencia es una virtud.",
    autor: "Proverbio popular",
    nombre: "Refrán",
    textColor: "white",
  },
  {
    id: 27,
    texto: "El hombre es un lobo para el hombre.",
    autor: "Thomas Hobbes",
    nombre: "Leviatán",
    textColor: "white",
  },
  {
    id: 28,
    texto: "El fin justifica los medios.",
    autor: "Nicolás Maquiavelo",
    nombre: "El Príncipe",
    textColor: "white",
  },
  {
    id: 29,
    texto: "No hay nada nuevo bajo el sol.",
    autor: "Eclesiastés",
    nombre: "La Biblia",
    textColor: "white",
  },
  {
    id: 30,
    texto: "La libertad consiste en ser dueños de nuestra propia vida.",
    autor: "Platón",
    nombre: "Diálogos",
    textColor: "white",
  },
  {
    id: 31,
    texto: "La verdadera sabiduría está en reconocer la propia ignorancia.",
    autor: "Sócrates",
    nombre: "Diálogos de Platón",
    textColor: "white",
  },
  {
    id: 32,
    texto: "El amor es la fuerza más poderosa del mundo.",
    autor: "Mahatma Gandhi",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 33,
    texto: "La vida es un sueño, y los sueños, sueños son.",
    autor: "Pedro Calderón de la Barca",
    nombre: "La vida es sueño",
    textColor: "white",
  },
  {
    id: 34,
    texto: "No hay mayor riqueza que la salud.",
    autor: "Virgilio",
    nombre: "Éneida",
    textColor: "white",
  },
  {
    id: 35,
    texto: "La historia se repite.",
    autor: "Cicerón",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 36,
    texto:
      "La vida es como una caja de chocolates, nunca sabes lo que te va a tocar.",
    autor: "Forrest Gump",
    nombre: "Película: Forrest Gump",
    textColor: "white",
  },
  {
    id: 37,
    texto: "El amor todo lo puede.",
    autor: "Virgilio",
    nombre: "Églogas",
    textColor: "white",
  },
  {
    id: 38,
    texto: "La ignorancia es la noche de la mente.",
    autor: "Confucio",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 39,
    texto: "La vida es un viaje, no un destino.",
    autor: "Ralph Waldo Emerson",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 40,
    texto: "La vida es corta, vive intensamente.",
    autor: "Proverbio popular",
    nombre: "Refrán",
    textColor: "white",
  },
];
