export const questionPlay = [
  {
    id: 1,
    texto: "La vida es bella.",
    autor: "Roberto Benigni",
    nombre: "Película: La vida es bella",
    textColor: "white",
  },
  {
    id: 2,
    texto: "El tiempo es oro.",
    autor: "Proverbio popular",
    nombre: "Refrán",
    textColor: "white",
  },
  {
    id: 3,
    texto: "Carpe diem.",
    autor: "Horacio",
    nombre: "Odas",
    textColor: "white",
  },
  {
    id: 4,
    texto: "Vive y deja vivir.",
    autor: "Refrán popular",
    nombre: "Refrán",
    textColor: "white",
  },
  {
    id: 5,
    texto: "El saber no ocupa lugar.",
    autor: "Proverbio popular",
    nombre: "Refrán",
    textColor: "white",
  },
  {
    id: 6,
    texto: "La unión hace la fuerza.",
    autor: "Esopo",
    nombre: "Fábulas de Esopo",
    textColor: "white",
  },
  {
    id: 7,
    texto: "Más vale tarde que nunca.",
    autor: "Geoffrey Chaucer",
    nombre: "Los cuentos de Canterbury",
    textColor: "white",
  },
  {
    id: 8,
    texto: "La práctica hace al maestro.",
    autor: "Proverbio popular",
    nombre: "Refrán",
    textColor: "white",
  },
  {
    id: 9,
    texto: "A mal tiempo, buena cara.",
    autor: "Proverbio popular",
    nombre: "Refrán",
    textColor: "white",
  },
  {
    id: 10,
    texto: "El tiempo lo cura todo.",
    autor: "Proverbio popular",
    nombre: "Refrán",
    textColor: "white",
  },
  {
    id: 11,
    texto: "Ojos que no ven, corazón que no siente.",
    autor: "Proverbio popular",
    nombre: "Refrán",
    textColor: "white",
  },
  {
    id: 12,
    texto: "Haz el bien sin mirar a quién.",
    autor: "Proverbio popular",
    nombre: "Refrán",
    textColor: "white",
  },
  {
    id: 13,
    texto: "Quien mucho abarca, poco aprieta.",
    autor: "Proverbio popular",
    nombre: "Refrán",
    textColor: "white",
  },
  {
    id: 14,
    texto: "El que persevera, alcanza.",
    autor: "Proverbio popular",
    nombre: "Refrán",
    textColor: "white",
  },
  {
    id: 15,
    texto: "A quien madruga, Dios le ayuda.",
    autor: "Proverbio popular",
    nombre: "Refrán",
    textColor: "white",
  },
  {
    id: 16,
    texto: "No hay mal que por bien no venga.",
    autor: "Proverbio popular",
    nombre: "Refrán",
    textColor: "white",
  },
  {
    id: 17,
    texto: "Más vale prevenir que curar.",
    autor: "Proverbio popular",
    nombre: "Refrán",
    textColor: "white",
  },
  {
    id: 18,
    texto: "De tal palo, tal astilla.",
    autor: "Proverbio popular",
    nombre: "Refrán",
    textColor: "white",
  },
  {
    id: 19,
    texto: "En casa de herrero, cuchillo de palo.",
    autor: "Proverbio popular",
    nombre: "Refrán",
    textColor: "white",
  },
  {
    id: 20,
    texto: "El conocimiento es poder.",
    autor: "Francis Bacon",
    nombre: "Meditationes Sacrae",
    textColor: "white",
  },
  {
    id: 21,
    texto: "Divide y vencerás.",
    autor: "Julio César",
    nombre: "Estrategia militar",
    textColor: "white",
  },
  {
    id: 22,
    texto: "Pienso, luego existo.",
    autor: "René Descartes",
    nombre: "Discurso del método",
    textColor: "white",
  },
  {
    id: 23,
    texto: "Ser o no ser, esa es la cuestión.",
    autor: "William Shakespeare",
    nombre: "Hamlet",
    textColor: "white",
  },
  {
    id: 24,
    texto: "La esperanza es lo último que se pierde.",
    autor: "Proverbio popular",
    nombre: "Refrán",
    textColor: "white",
  },
  {
    id: 25,
    texto: "Lo que no te mata, te hace más fuerte.",
    autor: "Friedrich Nietzsche",
    nombre: "Crepúsculo de los ídolos",
    textColor: "white",
  },
  {
    id: 26,
    texto: "La paciencia es una virtud.",
    autor: "Proverbio popular",
    nombre: "Refrán",
    textColor: "white",
  },
  {
    id: 27,
    texto: "El hombre es un lobo para el hombre.",
    autor: "Thomas Hobbes",
    nombre: "Leviatán",
    textColor: "white",
  },
  {
    id: 28,
    texto: "El fin justifica los medios.",
    autor: "Nicolás Maquiavelo",
    nombre: "El Príncipe",
    textColor: "white",
  },
  {
    id: 29,
    texto: "No hay nada nuevo bajo el sol.",
    autor: "Eclesiastés",
    nombre: "La Biblia",
    textColor: "white",
  },
  {
    id: 30,
    texto: "La libertad consiste en ser dueños de nuestra propia vida.",
    autor: "Platón",
    nombre: "Diálogos",
    textColor: "white",
  },
  {
    id: 31,
    texto: "La verdadera sabiduría está en reconocer la propia ignorancia.",
    autor: "Sócrates",
    nombre: "Diálogos de Platón",
    textColor: "white",
  },
  {
    id: 32,
    texto: "El amor es la fuerza más poderosa del mundo.",
    autor: "Mahatma Gandhi",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 33,
    texto: "La vida es un sueño, y los sueños, sueños son.",
    autor: "Pedro Calderón de la Barca",
    nombre: "La vida es sueño",
    textColor: "white",
  },
  {
    id: 34,
    texto: "No hay mayor riqueza que la salud.",
    autor: "Virgilio",
    nombre: "Éneida",
    textColor: "white",
  },
  {
    id: 35,
    texto: "La historia se repite.",
    autor: "Cicerón",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 36,
    texto:
      "La vida es como una caja de chocolates, nunca sabes lo que te va a tocar.",
    autor: "Forrest Gump",
    nombre: "Película: Forrest Gump",
    textColor: "white",
  },
  {
    id: 37,
    texto: "El amor todo lo puede.",
    autor: "Virgilio",
    nombre: "Églogas",
    textColor: "white",
  },
  {
    id: 38,
    texto: "La ignorancia es la noche de la mente.",
    autor: "Confucio",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 39,
    texto: "La vida es un viaje, no un destino.",
    autor: "Ralph Waldo Emerson",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 40,
    texto: "La vida es corta, vive intensamente.",
    autor: "Proverbio popular",
    nombre: "Refrán",
    textColor: "white",
  },
  {
    id: 41,
    texto: "No hay camino para la paz, la paz es el camino.",
    autor: "Mahatma Gandhi",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 42,
    texto: "El éxito es la suma de pequeños esfuerzos repetidos día tras día.",
    autor: "Robert Collier",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 43,
    texto:
      "La vida no se trata de encontrarte a ti mismo, sino de crearte a ti mismo.",
    autor: "George Bernard Shaw",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 44,
    texto: "No cuentes los días, haz que los días cuenten.",
    autor: "Muhammad Ali",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 45,
    texto:
      "La vida es lo que pasa mientras estás ocupado haciendo otros planes.",
    autor: "John Lennon",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 46,
    texto: "La única forma de hacer un gran trabajo es amar lo que haces.",
    autor: "Steve Jobs",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 47,
    texto:
      "El único límite a nuestros logros de mañana es nuestras dudas de hoy.",
    autor: "Franklin D. Roosevelt",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 48,
    texto:
      "El mayor error que puedes cometer es el de no hacer nada porque solo puedes hacer un poco.",
    autor: "Sydney Smith",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 49,
    texto:
      "El éxito no es la clave de la felicidad. La felicidad es la clave del éxito.",
    autor: "Albert Schweitzer",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 50,
    texto:
      "No es lo que tienes, sino cómo usas lo que tienes lo que marca la diferencia.",
    autor: "Zig Ziglar",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 51,
    texto: "La imaginación es más importante que el conocimiento.",
    autor: "Albert Einstein",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 52,
    texto: "No podemos ayudar a todos, pero todos pueden ayudar a alguien.",
    autor: "Ronald Reagan",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 53,
    texto:
      "La vida es realmente simple, pero insistimos en hacerla complicada.",
    autor: "Confucio",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 54,
    texto: "El único modo de hacer un gran trabajo es amar lo que haces.",
    autor: "Steve Jobs",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 55,
    texto: "El fracaso es éxito si aprendemos de él.",
    autor: "Malcolm Forbes",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 56,
    texto: "La vida es una aventura, atrévete.",
    autor: "Teresa de Calcuta",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 57,
    texto:
      "La mayor gloria en la vida no consiste en no caer, sino en levantarnos cada vez que caemos.",
    autor: "Nelson Mandela",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 58,
    texto: "La vida es una obra de teatro que no permite ensayos.",
    autor: "Charles Chaplin",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 59,
    texto:
      "El éxito no es la clave de la felicidad. La felicidad es la clave del éxito.",
    autor: "Albert Schweitzer",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 60,
    texto:
      "El mejor momento para plantar un árbol fue hace veinte años. El segundo mejor momento es ahora.",
    autor: "Proverbio chino",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 61,
    texto: "Nunca es demasiado tarde para ser lo que podrías haber sido.",
    autor: "George Eliot",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 62,
    texto:
      "La vida es un 10% lo que te ocurre y un 90% cómo reaccionas a ello.",
    autor: "Charles R. Swindoll",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 63,
    texto: "La verdadera sabiduría está en reconocer la propia ignorancia.",
    autor: "Sócrates",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 64,
    texto:
      "El único límite a nuestros logros de mañana es nuestras dudas de hoy.",
    autor: "Franklin D. Roosevelt",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 65,
    texto: "El único modo de hacer un gran trabajo es amar lo que haces.",
    autor: "Steve Jobs",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 66,
    texto: "El fracaso es éxito si aprendemos de él.",
    autor: "Malcolm Forbes",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 67,
    texto: "La vida es una aventura, atrévete.",
    autor: "Teresa de Calcuta",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 68,
    texto:
      "El mejor momento para plantar un árbol fue hace veinte años. El segundo mejor momento es ahora.",
    autor: "Proverbio chino",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 69,
    texto: "Nunca es demasiado tarde para ser lo que podrías haber sido.",
    autor: "George Eliot",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 70,
    texto:
      "La vida es un 10% lo que te ocurre y un 90% cómo reaccionas a ello.",
    autor: "Charles R. Swindoll",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 71,
    texto: "No cuentes los días, haz que los días cuenten.",
    autor: "Muhammad Ali",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 72,
    texto:
      "El éxito no es la clave de la felicidad. La felicidad es la clave del éxito.",
    autor: "Albert Schweitzer",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 73,
    texto: "El conocimiento es poder.",
    autor: "Francis Bacon",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 74,
    texto: "La imaginación es más importante que el conocimiento.",
    autor: "Albert Einstein",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 75,
    texto: "El éxito es la suma de pequeños esfuerzos repetidos día tras día.",
    autor: "Robert Collier",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 76,
    texto:
      "La vida no se trata de encontrarte a ti mismo, sino de crearte a ti mismo.",
    autor: "George Bernard Shaw",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 77,
    texto:
      "El único límite a nuestros logros de mañana es nuestras dudas de hoy.",
    autor: "Franklin D. Roosevelt",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 78,
    texto:
      "El mayor error que puedes cometer es el de no hacer nada porque solo puedes hacer un poco.",
    autor: "Sydney Smith",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 79,
    texto:
      "La vida es realmente simple, pero insistimos en hacerla complicada.",
    autor: "Confucio",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 80,
    texto: "El único modo de hacer un gran trabajo es amar lo que haces.",
    autor: "Steve Jobs",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 81,
    texto: "El fracaso es éxito si aprendemos de él.",
    autor: "Malcolm Forbes",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 82,
    texto: "La vida es una aventura, atrévete.",
    autor: "Teresa de Calcuta",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 83,
    texto:
      "La mayor gloria en la vida no consiste en no caer, sino en levantarnos cada vez que caemos.",
    autor: "Nelson Mandela",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 84,
    texto: "La vida es una obra de teatro que no permite ensayos.",
    autor: "Charles Chaplin",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 85,
    texto:
      "El éxito no es la clave de la felicidad. La felicidad es la clave del éxito.",
    autor: "Albert Schweitzer",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 86,
    texto:
      "El mejor momento para plantar un árbol fue hace veinte años. El segundo mejor momento es ahora.",
    autor: "Proverbio chino",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 87,
    texto: "Nunca es demasiado tarde para ser lo que podrías haber sido.",
    autor: "George Eliot",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 88,
    texto:
      "La vida es un 10% lo que te ocurre y un 90% cómo reaccionas a ello.",
    autor: "Charles R. Swindoll",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 89,
    texto: "No cuentes los días, haz que los días cuenten.",
    autor: "Muhammad Ali",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 90,
    texto:
      "El éxito no es la clave de la felicidad. La felicidad es la clave del éxito.",
    autor: "Albert Schweitzer",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 91,
    texto: "El conocimiento es poder.",
    autor: "Franc is Bacon",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 92,
    texto: "La imaginación es más importante que el conocimiento.",
    autor: "Albert Einstein",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 93,
    texto: "El éxito es la suma de pequeños esfuerzos repetidos día tras día.",
    autor: "Robert Collier",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 94,
    texto:
      "La vida no se trata de encontrarte a ti mismo, sino de crearte a ti mismo.",
    autor: "George Bernard Shaw",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 95,
    texto:
      "El único límite a nuestros logros de mañana es nuestras dudas de hoy.",
    autor: "Franklin D. Roosevelt",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 96,
    texto:
      "El mayor error que puedes cometer es el de no hacer nada porque solo puedes hacer un poco.",
    autor: "Sydney Smith",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 97,
    texto:
      "La vida es realmente simple, pero insistimos en hacerla complicada.",
    autor: "Confucio",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 98,
    texto: "El único modo de hacer un gran trabajo es amar lo que haces.",
    autor: "Steve Jobs",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 99,
    texto: "El fracaso es éxito si aprendemos de él.",
    autor: "Malcolm Forbes",
    nombre: "Frase célebre",
    textColor: "white",
  },
  {
    id: 100,
    texto: "La vida es una aventura, atrévete.",
    autor: "Teresa de Calcuta",
    nombre: "Frase célebre",
    textColor: "white",
  },
];
