export const wordPlay = [
  {
    id: 1,
    texto: "Caballo",
    autor: "Ninguno",
    nombre: "Caballo",
    textColor: "white",
  },
  {
    id: 2,
    texto: "Amor",
    autor: "Ninguno",
    nombre: "Amor",
    textColor: "white",
  },
  {
    id: 3,
    texto: "Amistad",
    autor: "Ninguno",
    nombre: "Amistad",
    textColor: "white",
  },
  {
    id: 4,
    texto: "Alegría",
    autor: "Ninguno",
    nombre: "Alegría",
    textColor: "white",
  },
  {
    id: 5,
    texto: "Aventura",
    autor: "Ninguno",
    nombre: "Aventura",
    textColor: "white",
  },
  {
    id: 6,
    texto: "Belleza",
    autor: "Ninguno",
    nombre: "Belleza",
    textColor: "white",
  },
  {
    id: 7,
    texto: "Bondad",
    autor: "Ninguno",
    nombre: "Bondad",
    textColor: "white",
  },
  {
    id: 8,
    texto: "Brillante",
    autor: "Ninguno",
    nombre: "Brillante",
    textColor: "white",
  },
  {
    id: 9,
    texto: "Calidez",
    autor: "Ninguno",
    nombre: "Calidez",
    textColor: "white",
  },
  {
    id: 10,
    texto: "Cariño",
    autor: "Ninguno",
    nombre: "Cariño",
    textColor: "white",
  },
  {
    id: 11,
    texto: "Compasión",
    autor: "Ninguno",
    nombre: "Compasión",
    textColor: "white",
  },
  {
    id: 12,
    texto: "Coraje",
    autor: "Ninguno",
    nombre: "Coraje",
    textColor: "white",
  },
  {
    id: 13,
    texto: "Creatividad",
    autor: "Ninguno",
    nombre: "Creatividad",
    textColor: "white",
  },
  {
    id: 14,
    texto: "Descubrimiento",
    autor: "Ninguno",
    nombre: "Descubrimiento",
    textColor: "white",
  },
  {
    id: 15,
    texto: "Dicha",
    autor: "Ninguno",
    nombre: "Dicha",
    textColor: "white",
  },
  {
    id: 16,
    texto: "Educación",
    autor: "Ninguno",
    nombre: "Educación",
    textColor: "white",
  },
  {
    id: 17,
    texto: "Emoción",
    autor: "Ninguno",
    nombre: "Emoción",
    textColor: "white",
  },
  {
    id: 18,
    texto: "Energía",
    autor: "Ninguno",
    nombre: "Energía",
    textColor: "white",
  },
  {
    id: 19,
    texto: "Entusiasmo",
    autor: "Ninguno",
    nombre: "Entusiasmo",
    textColor: "white",
  },
  {
    id: 20,
    texto: "Esperanza",
    autor: "Ninguno",
    nombre: "Esperanza",
    textColor: "white",
  },
  {
    id: 21,
    texto: "Esfuerzo",
    autor: "Ninguno",
    nombre: "Esfuerzo",
    textColor: "white",
  },
  {
    id: 22,
    texto: "Felicidad",
    autor: "Ninguno",
    nombre: "Felicidad",
    textColor: "white",
  },
  {
    id: 23,
    texto: "Fuerza",
    autor: "Ninguno",
    nombre: "Fuerza",
    textColor: "white",
  },
  {
    id: 24,
    texto: "Generosidad",
    autor: "Ninguno",
    nombre: "Generosidad",
    textColor: "white",
  },
  {
    id: 25,
    texto: "Gratitud",
    autor: "Ninguno",
    nombre: "Gratitud",
    textColor: "white",
  },
  {
    id: 26,
    texto: "Habilidad",
    autor: "Ninguno",
    nombre: "Habilidad",
    textColor: "white",
  },
  {
    id: 27,
    texto: "Honestidad",
    autor: "Ninguno",
    nombre: "Honestidad",
    textColor: "white",
  },
  {
    id: 28,
    texto: "Imaginación",
    autor: "Ninguno",
    nombre: "Imaginación",
    textColor: "white",
  },
  {
    id: 29,
    texto: "Inspiración",
    autor: "Ninguno",
    nombre: "Inspiración",
    textColor: "white",
  },
  {
    id: 30,
    texto: "Inteligencia",
    autor: "Ninguno",
    nombre: "Inteligencia",
    textColor: "white",
  },
  {
    id: 31,
    texto: "Integridad",
    autor: "Ninguno",
    nombre: "Integridad",
    textColor: "white",
  },
  {
    id: 32,
    texto: "Jubilación",
    autor: "Ninguno",
    nombre: "Jubilación",
    textColor: "white",
  },
  {
    id: 33,
    texto: "Justicia",
    autor: "Ninguno",
    nombre: "Justicia",
    textColor: "white",
  },
  {
    id: 34,
    texto: "Libertad",
    autor: "Ninguno",
    nombre: "Libertad",
    textColor: "white",
  },
  {
    id: 35,
    texto: "Liderazgo",
    autor: "Ninguno",
    nombre: "Liderazgo",
    textColor: "white",
  },
  {
    id: 36,
    texto: "Maravilla",
    autor: "Ninguno",
    nombre: "Maravilla",
    textColor: "white",
  },
  {
    id: 37,
    texto: "Motivación",
    autor: "Ninguno",
    nombre: "Motivación",
    textColor: "white",
  },
  {
    id: 38,
    texto: "Optimismo",
    autor: "Ninguno",
    nombre: "Optimismo",
    textColor: "white",
  },
  {
    id: 39,
    texto: "Paciencia",
    autor: "Ninguno",
    nombre: "Paciencia",
    textColor: "white",
  },
  {
    id: 40,
    texto: "Pasión",
    autor: "Ninguno",
    nombre: "Pasión",
    textColor: "white",
  },
  {
    id: 41,
    texto: "Perseverancia",
    autor: "Ninguno",
    nombre: "Perseverancia",
    textColor: "white",
  },
  {
    id: 42,
    texto: "Placer",
    autor: "Ninguno",
    nombre: "Placer",
    textColor: "white",
  },
  {
    id: 43,
    texto: "Positividad",
    autor: "Ninguno",
    nombre: "Positividad",
    textColor: "white",
  },
  {
    id: 44,
    texto: "Prosperidad",
    autor: "Ninguno",
    nombre: "Prosperidad",
    textColor: "white",
  },
  { id: 45, texto: "Paz", autor: "Ninguno", nombre: "Paz", textColor: "white" },
  {
    id: 46,
    texto: "Respeto",
    autor: "Ninguno",
    nombre: "Respeto",
    textColor: "white",
  },
  {
    id: 47,
    texto: "Sabiduría",
    autor: "Ninguno",
    nombre: "Sabiduría",
    textColor: "white",
  },
  {
    id: 48,
    texto: "Solidaridad",
    autor: "Ninguno",
    nombre: "Solidaridad",
    textColor: "white",
  },
  {
    id: 49,
    texto: "Superación",
    autor: "Ninguno",
    nombre: "Superación",
    textColor: "white",
  },
  {
    id: 50,
    texto: "Tenacidad",
    autor: "Ninguno",
    nombre: "Tenacidad",
    textColor: "white",
  },
  {
    id: 51,
    texto: "Tranquilidad",
    autor: "Ninguno",
    nombre: "Tranquilidad",
    textColor: "white",
  },
  {
    id: 52,
    texto: "Valor",
    autor: "Ninguno",
    nombre: "Valor",
    textColor: "white",
  },
  {
    id: 53,
    texto: "Veracidad",
    autor: "Ninguno",
    nombre: "Veracidad",
    textColor: "white",
  },
  {
    id: 54,
    texto: "Vitalidad",
    autor: "Ninguno",
    nombre: "Vitalidad",
    textColor: "white",
  },
  {
    id: 55,
    texto: "Voluntad",
    autor: "Ninguno",
    nombre: "Voluntad",
    textColor: "white",
  },
  {
    id: 56,
    texto: "Armonía",
    autor: "Ninguno",
    nombre: "Armonía",
    textColor: "white",
  },
  {
    id: 57,
    texto: "Bienestar",
    autor: "Ninguno",
    nombre: "Bienestar",
    textColor: "white",
  },
  {
    id: 58,
    texto: "Compromiso",
    autor: "Ninguno",
    nombre: "Compromiso",
    textColor: "white",
  },
  {
    id: 59,
    texto: "Crecimiento",
    autor: "Ninguno",
    nombre: "Crecimiento",
    textColor: "white",
  },
  {
    id: 60,
    texto: "Dedicación",
    autor: "Ninguno",
    nombre: "Dedicación",
    textColor: "white",
  },
  {
    id: 61,
    texto: "Determinación",
    autor: "Ninguno",
    nombre: "Determinación",
    textColor: "white",
  },
  {
    id: 62,
    texto: "Dignidad",
    autor: "Ninguno",
    nombre: "Dignidad",
    textColor: "white",
  },
  {
    id: 63,
    texto: "Educación",
    autor: "Ninguno",
    nombre: "Educación",
    textColor: "white",
  },
  {
    id: 64,
    texto: "Empatía",
    autor: "Ninguno",
    nombre: "Empatía",
    textColor: "white",
  },
  {
    id: 65,
    texto: "Equilibrio",
    autor: "Ninguno",
    nombre: "Equilibrio",
    textColor: "white",
  },
  {
    id: 66,
    texto: "Éxito",
    autor: "Ninguno",
    nombre: "Éxito",
    textColor: "white",
  },
  {
    id: 67,
    texto: "Honra",
    autor: "Ninguno",
    nombre: "Honra",
    textColor: "white",
  },
  {
    id: 68,
    texto: "Igualdad",
    autor: "Ninguno",
    nombre: "Igualdad",
    textColor: "white",
  },
  {
    id: 69,
    texto: "Inclusión",
    autor: "Ninguno",
    nombre: "Inclusión",
    textColor: "white",
  },
  {
    id: 70,
    texto: "Innovación",
    autor: "Ninguno",
    nombre: "Innovación",
    textColor: "white",
  },
  {
    id: 71,
    texto: "Lealtad",
    autor: "Ninguno",
    nombre: "Lealtad",
    textColor: "white",
  },
  {
    id: 72,
    texto: "Logro",
    autor: "Ninguno",
    nombre: "Logro",
    textColor: "white",
  },
  {
    id: 73,
    texto: "Madurez",
    autor: "Ninguno",
    nombre: "Madurez",
    textColor: "white",
  },
  {
    id: 74,
    texto: "Memoria",
    autor: "Ninguno",
    nombre: "Memoria",
    textColor: "white",
  },
  {
    id: 75,
    texto: "Optimismo",
    autor: "Ninguno",
    nombre: "Optimismo",
    textColor: "white",
  },
  {
    id: 76,
    texto: "Paciencia",
    autor: "Ninguno",
    nombre: "Paciencia",
    textColor: "white",
  },
  {
    id: 77,
    texto: "Perfección",
    autor: "Ninguno",
    nombre: "Perfección",
    textColor: "white",
  },
  {
    id: 78,
    texto: "Plenitud",
    autor: "Ninguno",
    nombre: "Plenitud",
    textColor: "white",
  },
  {
    id: 79,
    texto: "Potencial",
    autor: "Ninguno",
    nombre: "Potencial",
    textColor: "white",
  },
  {
    id: 80,
    texto: "Progreso",
    autor: "Ninguno",
    nombre: "Progreso",
    textColor: "white",
  },
  {
    id: 81,
    texto: "Realización",
    autor: "Ninguno",
    nombre: "Realización",
    textColor: "white",
  },
  {
    id: 82,
    texto: "Reconocimiento",
    autor: "Ninguno",
    nombre: "Reconocimiento",
    textColor: "white",
  },
  {
    id: 83,
    texto: "Reflexión",
    autor: "Ninguno",
    nombre: "Reflexión",
    textColor: "white",
  },
  {
    id: 84,
    texto: "Respeto",
    autor: "Ninguno",
    nombre: "Respeto",
    textColor: "white",
  },
  {
    id: 85,
    texto: "Responsabilidad",
    autor: "Ninguno",
    nombre: "Responsabilidad",
    textColor: "white",
  },
  {
    id: 86,
    texto: "Sabiduría",
    autor: "Ninguno",
    nombre: "Sabiduría",
    textColor: "white",
  },
  {
    id: 87,
    texto: "Salud",
    autor: "Ninguno",
    nombre: "Salud",
    textColor: "white",
  },
  {
    id: 88,
    texto: "Satisfacción",
    autor: "Ninguno",
    nombre: "Satisfacción",
    textColor: "white",
  },
  {
    id: 89,
    texto: "Solidaridad",
    autor: "Ninguno",
    nombre: "Solidaridad",
    textColor: "white",
  },
  {
    id: 90,
    texto: "Templanza",
    autor: "Ninguno",
    nombre: "Templanza",
    textColor: "white",
  },
  {
    id: 91,
    texto: "Tolerancia",
    autor: "Ninguno",
    nombre: "Tolerancia",
    textColor: "white",
  },
  {
    id: 92,
    texto: "Trabajo",
    autor: "Ninguno",
    nombre: "Trabajo",
    textColor: "white",
  },
  {
    id: 93,
    texto: "Unidad",
    autor: "Ninguno",
    nombre: "Unidad",
    textColor: "white",
  },
  {
    id: 94,
    texto: "Valentía",
    autor: "Ninguno",
    nombre: "Valentía",
    textColor: "white",
  },
  {
    id: 95,
    texto: "Virtud",
    autor: "Ninguno",
    nombre: "Virtud",
    textColor: "white",
  },
  {
    id: 96,
    texto: "Vitalidad",
    autor: "Ninguno",
    nombre: "Vitalidad",
    textColor: "white",
  },
  {
    id: 97,
    texto: "Voluntad",
    autor: "Ninguno",
    nombre: "Voluntad",
    textColor: "white",
  },
  {
    id: 98,
    texto: "Armonía",
    autor: "Ninguno",
    nombre: "Armonía",
    textColor: "white",
  },
  {
    id: 99,
    texto: "Bienestar",
    autor: "Ninguno",
    nombre: "Bienestar",
    textColor: "white",
  },
  {
    id: 100,
    texto: "Compromiso",
    autor: "Ninguno",
    nombre: "Compromiso",
    textColor: "white",
  },
];
